[package]
name = "client"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1"
async-trait = "0.1"
console_error_panic_hook = "0.1"
derive_more = "0.99"
extend = "1.1"
hobo = "0.1"
#wasm-timer = "0.2"
js-sys = "0.3"
log = "0.4"
once_cell = "1.7.2"
#postcard = { version = "0.7", features = ["use-std"] }
#wasm-bindgen-backend = "=0.2.74"
#web-sys = "=0.3.51"
reqwest = { version = "0.11", features = ["gzip", "brotli", "json", "rustls-tls", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"
shared = { path = "../shared" }
#slotmap = { version = "1", features = ["unstable"] }
smart-default = "0.6"
#strum = { version = "0.20", features = ["derive"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"
