[workspace]

members = [
	"server",
	"shared",
	"client",
#	"tools",
]

[patch.crates-io]
hobo = { path = "client/hobo/lib" }
hobo_derive = { path = "client/hobo/derive" }
hobo_css = { path = "client/hobo/css" }
hobo_css_macros = { path = "client/hobo/css/macros" }

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
