[workspace]

members = [
	"server",
	"shared",
	"client",
#	"tools",
]

exclude = [
	"hobo",
]

[patch.crates-io]
hobo = { path = "hobo/lib" }
hobo_derive = { path = "hobo/derive" }
hobo_css = { path = "hobo/css" }
hobo_css_macros = { path = "hobo/css/macros" }

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
