[package]
name = "server"
version = "0.1.0"
edition = "2018"

[dependencies]

actix = "0.11"
actix-web-actors = "=4.0.0-beta.4"
actix-web = { version = "=4.0.0-beta.5", features = ["rustls"] }
actix-service = "=2.0.0-beta.5"
actix-files = "=0.6.0-beta.4"
actix-cors = "=0.6.0-beta.1"
reqwest = { version = "0.11", features = ["gzip", "brotli", "json", "rustls-tls", "stream"] }
rustls = "0.19"
serde = "1"
serde_json = "1"
lazy_static = "1"
shared = { path = "../shared" }
log = "0.4"
log-derive = "0.4"
env_logger = "0.8"
toml = "0.5"
anyhow = "1"
tokio = { version = "1", features = ["full"] }
postcard = { version = "0.7", features = ["use-std"] }
uuid = { version = "0.8", features = ["serde"] }
once_cell = "1"
minifier = "0.0.39"
minify = "1"
futures = "0.3"
chrono = { version = "0.4", features = ["serde"] }
