# http_port = 80
http_port = 63333
# https_port = 443
# https_port = 3120
https_port = 63333
https = false

[ssl]
cert = "/etc/letsencrypt/live/gremy.co.uk/fullchain.pem"
key = "/etc/letsencrypt/live/gremy.co.uk/privkey.pem"
# cert = "C:/Certbot/live/gremy.co.uk/fullchain.pem"
# key = "C:/Certbot/live/gremy.co.uk/privkey.pem"
