[package]
name = "shared"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1"
log = "0.4"
once_cell = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
wasm-bindgen-futures = "0.4"
reqwest = "0.12"
tap = "1"
