[package]
name = "shared"
version = "0.1.0"
edition = "2018"

[dependencies]
toml = "0.5"
serde = { version = "1", features = ["derive"] }
uuid = { version = "0.8", features = ["serde"] }
once_cell = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
actix = "0.11"
